### ISSUE TITLE
Required column and defaults

### ISSUE THREAD

**Issue by boan-jfm** [mindplay-dk/sql#44]
If a default is specified for a required column, it may use this instead of throwing a runtime exception.

**Comment by mindplay-dk** [comment]
This is really poorly documented (and not even covered by a test) but "required" currently means "are you required to specify a value when you insert one of these" - see here:

https://github.com/mindplay-dk/sql/blob/master/src/model/query/InsertQuery.php#L80-L81

The thinking was, if the database schema requires you to specify a value, you should be required to do so in your software - the "default" value is a default only for columns where you *aren't* required to specify a value, e.g. has nothing to do with whether the underlying database *schema* has a default.

As said, this is really poorly documented, but I think it makes sense? Required means required - which means you must specify a value. If that wasn't the case, you could just set a default at the schema-level and not specify a value in the INSERT query at all, right?

**Comment by boan-jfm** [comment]
> If that wasn't the case, you could just set a default at the schema-level and not specify a value in the INSERT query at all, right?

If you mean this:
```
    public function response_code($alias): Column
    {
        return $this->requiredColumn(__FUNCTION__, IntType::class, $alias, 0);
    }
```
Then, it doens't work (which is the issue), you need to add it in your insert in the repository as it is now:

```
...
$this->db
            ->insert($table)
            ->add([
                $table->response_code->getName() => 0,
            ])
...
```

**Comment by mindplay-dk** [comment]
@boan2010 no, you're using `requiredColumn()` - it produces a `Column` with `$required = true`. Attempting to `add()` without specifying the value isn't supposed to work. Use `optionalColumn()` to define a `Column` with `$required = false` and the default will be assigned.
